spring.application.name=Omniflash.info

# Build the clean URL without credentials
spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}

# Pass the credentials separately
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}

# Specify the driver
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
